---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ loki_dependencies }}"

- name: Create the loki group
  group:
    name: "{{ loki_system_group }}"
    state: present
    system: true
  when:
    - loki_system_group != "root"

- name: Create the loki user
  user:
    name: "{{ loki_system_user }}"
    groups: "{{ loki_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when:
    - loki_system_user != "root"

- name: create loki config directory
  file:
    path: "{{ loki_config_dir }}"
    state: directory
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
    mode: 0755

- name: Download loki binary
  become: false
  get_url:
    url: "{{ base_download_url }}{{ versioned_download_url }}"
    dest: "/tmp"

- name: Unpack loki binary
  become: false
  unarchive:
    src: "/tmp/loki-linux-{{ go_arch }}.zip"
    dest: "/tmp"
    remote_src: true

- name: Create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Propagate loki binaries
  copy:
    src: "/tmp/loki-linux-{{ go_arch }}"
    dest: "/usr/local/bin/loki"
    mode: 0755
    owner: root
    group: root
    remote_src: true
  notify: restart loki
  when: not ansible_check_mode
